- .circleci/config.yml
- Makefile
- codecov.yml
> add circleci and codecov

- Makefile
> add go-mod-cache

- Makefile
- README.md
- app/genesis/genesis.json
- cmd/okchaincli/main.go
- go.mod
- x/debug/alias.go
- x/debug/client/cli/debug.go
- x/debug/keeper/keeper.go
- x/debug/keeper/querier.go
- x/debug/module.go
- x/debug/types/codec.go
- x/debug/types/errors.go
- x/debug/types/expected_keepers.go
- x/debug/types/keys.go
- x/debug/types/msg.go
> bump to CosmosSDK v0.37.9 in Makefile

- x/staking/common_test.go
- x/staking/delegator_test.go
- x/staking/validator_state_machine_test.go
- x/staking/validator_test.go
> replace fmt.Printf with t.Logf

- go.mod
> standardize the module version by the semver rule

- CODEOWNERS
> add code codeowners

- CODEOWNERS
> add code owner

- CODEOWNERS
> add code owner rule

- .circleci/config.yml
> only execute ut once

- app/genesis/genesis.json
- cmd/okchaind/testnet.go
- x/debug/client/cli/debug.go
> Change system fee to gas fee

- x/order/match/periodicauction/fill.go
- x/order/match/periodicauction/fill_test.go
- x/order/match/periodicauction/impl.go
- x/order/match/periodicauction/impl_test.go
- x/order/match/periodicauction/match.go
- x/order/match/periodicauction/match_test.go
> add periodic auction

- x/order/keeper/expect_keepers.go
- x/order/keeper/invariant.go
- x/order/keeper/invariant_test.go
- x/order/module.go
- x/token/genesis.go
- x/token/genesis_test.go
- x/token/keeper.go
- x/token/token_test.go
- x/token/types/keys.go
> add invariant for token modeule and order module

- x/order/keeper/expect_keepers.go
- x/order/keeper/invariant.go
- x/token/genesis.go
- x/token/genesis_test.go
- x/token/keeper.go
- x/token/keeper_test.go
- x/token/legacy/v0_9/migrate.go
- x/token/legacy/v0_9/types.go
- x/token/types/util.go
- x/token/types/util_test.go
> standardize var name and func name

- x/backend/config/config.go
> fix backend default config

- .circleci/config.yml
> open order ut

- cmd/okchaind/testnet.go
- x/gov/keeper/querier_test.go
- x/gov/keeper/tally_test.go
- x/gov/keeper/test_common.go
- x/staking/common_test.go
- x/staking/delegator_test.go
- x/staking/handler.go
- x/staking/handler_test.go
- x/staking/handler_vote_test.go
- x/staking/keeper/invariants.go
- x/staking/keeper/min_self_delegation.go
- x/staking/types/params.go
- x/staking/types/validator.go
- x/staking/validator_state_machine_test.go
- x/staking/validator_test.go
Closes: #38 
1. fix msd : 0.001okt
2. votes from fixed msd : 1
______
For Admin Use:
> FIX: issue #38

- app/genesis/genesis.json
- go.mod
- go.sum
> bump to cosmos sdk be5e2eaf65fe

- x/staking/handler_vote.go
FIX: ODEX-324 error msg reminder.
______
For Admin Use:
> FIX: ODEX-324 error msg reminder

- x/staking/delegator_test.go
- x/staking/handler_vote.go
- x/staking/keeper/proxy_test.go
- x/staking/types/errors.go
FIX:  a delegator was banned from proxy regsiter with keeping binding before.
______
For Admin Use:
> FIX: a delegator was banned from proxy regsiter with keeping binding before

- x/swap/client/cli/tx.go
- x/swap/handler.go
> add removeLiquidity to cli and fix a bug

- x/distribution/client/cli/query.go
- x/distribution/client/cli/tx.go
- x/distribution/types/fee_pool_test.go
- Fix #61
- Modify some annotation code
______
For Admin Use:
> add default demon coin to the annotation code of the distribution module

- x/staking/handler.go
- x/staking/keeper/params.go
- x/staking/legacy/v0_36/types.go
- x/staking/types/errors.go
- x/staking/types/params.go
- x/staking/types/params_test.go
Closes:  #47  
Fix issue #47 : remove the adaptable param `MinSelfDelegationLimited` and recover the ut related.
______
For Admin Use:
> remove the useless adaptable params - MinSelfDelegationLimited and recover the staking ut

- app/protocol/protocol_v0.go
- x/dex/genesis.go
- x/token/genesis.go
- fix issue #71
- add the initialiazation of module account in the stage of `initGenesis`
______
For Admin Use:
> init the module account at the stage of initGenesis

- x/token/types/params.go
- x/token/types/params_test.go
Close: #77 
Remove the deprecated base fee from token params.
______
For Admin Use:
> FIX: remove the deprecated base fee

- x/common/types/spot_errors.go
- x/dex/handler.go
- x/dex/keeper/keeper.go
- x/dex/keeper/querier.go
- x/dex/types/msgs.go
> x/dex: add error code

- go.mod
- go.sum
> update the tendermint version

- x/common/types/spot_errors.go
- x/dex/handler.go
- x/dex/keeper/keeper.go
- x/dex/keeper/querier.go
- x/dex/types/msgs.go
> x/dex: add spot error code

- x/common/types/asset_errors.go
- x/common/types/spot_errors.go
- x/order/handler.go
- x/order/handler_test.go
- x/order/keeper/querier.go
- x/order/keeper/querier_test.go
- x/order/types/msgs.go
> error code order

- x/order/keeper/disk_cache.go
- x/order/keeper/disk_cache_test.go
- x/order/keeper/keeper.go
- x/order/keeper/order_map_test.go
> update how disk cache initialized

- go.mod
- go.sum
> bump to cosmos-sdk v0.37.9-okchain3 and tendermint v0.32.10-okchain1

- x/backend/keeper/keeper.go
- x/backend/types/expected_keepers.go
- x/backend/types/tx.go
- x/backend/types/tx_test.go
- x/order/alias.go
- x/stream/expected_keeper.go
- x/stream/keeper_skeleton.go
- x/token/alias.go
- x/token/types/fee.go
> add stream expected keeper

- x/distribution/abci.go
- x/distribution/keeper/allocation.go
- optimize https://github.com/okex/okchain/issues/128
______
For Admin Use:
> optimize the logger output in distribution

- x/common/util_test.go
- x/dex/handler_test.go
- x/distribution/legacy/v0_36/migrate_test.go
- x/gov/keeper/tally_test.go
- x/order/handler_test.go
- x/order/keeper/disk_cache_test.go
- x/order/keeper/keeper_test.go
- x/order/types/order_test.go
- x/order/types/params_test.go
- x/staking/client/cli/tx.go
- x/staking/genesis_test.go
- x/staking/keeper/querier_test.go
- x/token/genesis_test.go
- x/token/token_test.go
- x/token/types/msgs_test.go
- x/token/types/params_test.go
- x/token/types/token_test.go
- x/token/types/util_test.go
> UT: change code to native token 

- x/token/types/params.go
- x/token/types/params_test.go
Close: #121 
Remove send fee from token params
______
For Admin Use:
> FIX: remove send fee from token params

- x/dex/types/msgs.go
> x/dex:  add check for list msg

- x/staking/common_test.go
- x/staking/delegator_test.go
- x/staking/handler_vote.go
Close: #133 
Fix the bug and append the ut for rebind.
______
For Admin Use:
> FIX: break off the relation between the delegator and original proxy before rebind

- x/order/client/cli/tx.go
> the gas flags should be displayed for new/cancel order transactions

- x/token/handler.go
- x/token/keeper_test.go
- x/token/token_test.go
- x/token/types/const.go
- x/token/types/params.go
- x/token/types/params_test.go
Close: #139 
______
For Admin Use:
> FIX: remove original multi-send fee from token module

- x/token/token_test.go
- x/token/types/params.go
- x/token/types/params_test.go
> update default fee of token

- Makefile
> add gcflag to enable all of the debug information

- x/staking/client/cli/query.go
- x/staking/common_test.go
- x/staking/keeper/querier.go
- x/staking/types/querier.go
Close: #164 
______
For Admin Use:
> FIX: Duplicated votes query information by REST way

- x/order/handler.go
- x/order/handler_test.go
- x/order/types/msgs.go
- x/order/types/params.go
- x/order/types/params_test.go
https://github.com/okex/okchain/issues/173
> fix issue#173: add order params to proposal

- Makefile
- app/genesis/genesis.json
> upgrade to version v0.11.0

- Makefile
- go.mod
- go.sum
> update go.mod and update target testnet in Makefile

- Makefile
> update GithubTop in Makefile

- x/dex/client/utils/utils.go
- x/distribution/client/cli/query.go
Close: #183 
______
For Admin Use:
> FIX: the description of distr query command

- x/staking/keeper/querier.go
Close: #166 (double commit)
______
For Admin Use:
> FIX: testnet add REST param 'all' to query all vals

- Makefile
> Makefile v0.10.7

- x/staking/keeper/val_state.go
- fix https://github.com/okex/okchain/issues/194
______
For Admin Use:
> ensure the validator would not be executed with the function bondedToUnbonding() repeatedly

- x/staking/keeper/invariants.go
Close: #193 
______
For Admin Use:
> FIX: DelegatorVotesInvariant doesn't cover the situation of any destroyed validator

- go.mod
> update the version of cosmos-sdk

- app/protocol/protocol_v0.go
- x/poolswap/genesis.go
- x/poolswap/handler.go
- x/poolswap/handler_test.go
- x/poolswap/keeper/keeper.go
- x/poolswap/types/params.go
> add feeRate to Params from poolswap

- x/dex/keeper/keeper.go
- x/dex/keeper/keeper_test.go
> duplicated token_pair_id 

- Makefile
- x/dex/keeper/proposal.go
> Fix: nil pointer after reject delist proposal 

- x/dex/keeper/keeper.go
- x/dex/keeper/keeper_test.go
> state machine broken

- x/dex/keeper/keeper.go
- x/dex/keeper/keeper_test.go
- x/dex/keeper/proposal.go
> fix token pair id duplicated issue

- x/token/handler.go
Close: #211 
______
For Admin Use:
> OPTIMIZE: check owner with the tool method that cosmos-sdk provides

- x/staking/handler_vote.go
> fix double bind bug

- x/token/genesis.go
- x/token/genesis_test.go
- x/token/types/util.go
> Fix token original symbol Regular expression

- app/app_test.go
- x/dex/keeper/keeper.go
- x/dex/keeper/proposal.go
- x/order/keeper/keeper.go
- x/staking/handler_vote.go
- x/staking/keeper/invariants.go
- x/staking/keeper/keeper.go
- x/staking/keeper/proxy.go
- x/staking/types/errors.go
- x/upgrade/keeper/keeper_deprecated.go
> (TESTNET) FIX: add sanity check

- app/app_test.go
- x/dex/handler.go
- x/dex/keeper/keeper.go
- x/dex/keeper/proposal.go
- x/dex/types/errors.go
- x/order/keeper/keeper.go
- x/staking/handler_shares.go
- x/staking/keeper/invariants.go
- x/staking/keeper/keeper.go
- x/staking/keeper/proxy.go
- x/staking/types/errors.go
- x/upgrade/keeper/keeper_deprecated.go
> FIX: add sanity check

- x/dex/alias.go
- x/dex/client/cli/tx.go
- x/dex/handler.go
- x/dex/handler_test.go
- x/dex/types/codec.go
- x/dex/types/msgs.go
- x/dex/types/msgs_test.go
- x/token/client/cli/query.go
> Remove: x/dex delist msg and x/token query cmd

- .github/ISSUE_TEMPLATE/bug-report.md
> update issue template

- .github/ISSUE_TEMPLATE/bug-report.md
> a typo in the issue template

- x/staking/types/msg_shares.go
Close: #233 
______
For Admin Use:
> FIX: typo in MsgDeposit

- Makefile
> Change version in Makefile

- .circleci/config.yml
- .github/ISSUE_TEMPLATE/bug-report.md
> update bug report template

- x/gov/keeper/querier.go
close #234
______
For Admin Use:
> Fix: add StatusFailed case when queryTally

- x/dex/types/msgs.go
> validate initial price of token pair

- x/distribution/keeper/allocation.go
Close: #265 
______
For Admin Use:
> FIX: correct annotation in distr

- x/poolswap/client/cli/tx.go
- x/poolswap/client/rest/tx.go
- x/poolswap/keeper/keeper.go
Close：#271 
______
For Admin Use:
> FIX: redundant errors and typo in poolswap

- x/dex/types/msgs.go
> fix issue#276

- x/backend/client/rest/rest.go
> validate request param: address and product

- app/protocol/protocol_v0.go
- x/token/genesis.go
- x/token/genesis_test.go
> fix issue#280: delete IssueOKT

- x/order/keeper/keeper.go
- x/order/keeper/order.go
- x/order/match/periodicauction/match.go
- x/order/match/periodicauction/match_test.go
- x/order/types/order.go
close #242 
______
For Admin Use:
> fix issue #242

- x/backend/keeper/keeper.go
- x/backend/types/klines.go
- x/backend/types/types.go
- x/backend/types/websocket.go
> add all_ticker_3s support

- go.mod
> update cosmos-sdk version to v0.37.9-testnet2

- app/protocol/protocol_v0.go
- x/backend/mock_test.go
- x/token/handler.go
- x/token/keeper.go
- x/token/token_test.go
- x/token/types/errors.go
Close: #312 
______
For Admin Use:
> FIX: add check to send/multi-send in token module

- go.sum
- x/token/handler.go
- x/token/types/errors.go
> FINISH: remove the bankkeeper check before any send/multi-send tx

- cmd/okchaind/main.go
- cmd/okchaind/replay.go
> local replay 

- x/ammswap/client/cli/tx.go
> add swap usage

- Makefile
> bump to v0.12.0

- x/ammswap/handler_test.go
> update x/ammswap ut

- Makefile
> version upgrade

- Makefile
- x/ammswap/client/cli/tx.go
- x/ammswap/handler.go
- x/ammswap/handler_test.go
- x/ammswap/types/msg_test.go
- x/ammswap/types/msgs.go
- x/ammswap/types/swap.go
> enhance creating swap pair

- x/staking/client/cli/tx.go
> x/staking: delete useless code

- x/token/keeper.go
> no suffix for usdk

- app/protocol/protocol_v0.go
- x/debug/client/cli/debug.go
- x/debug/keeper/keeper.go
- x/debug/keeper/querier.go
- x/debug/types/expected_keepers.go
- x/debug/types/keys.go
> add debug to check invariant

- x/ammswap/client/cli/query.go
- x/ammswap/client/cli/tx.go
- x/ammswap/handler.go
- x/ammswap/types/msgs.go
> add check for msg, optimize error message

- x/ammswap/handler.go
- x/ammswap/keeper/querier.go
- x/ammswap/types/msgs.go
> optimize error messages, add security check

- x/order/keeper/keeper.go
- x/order/keeper/keeper_test.go
- x/order/keeper/memory_cache.go
- x/order/keeper/memory_cache_test.go
> remove param cache from order keeper Cache

- Makefile
> bump to release/v0.13.0

- x/distribution/client/cli/query.go
- x/distribution/client/cli/tx.go
- x/distribution/module_test.go
- x/gov/client/cli/query.go
- x/staking/client/cli/query.go
- x/staking/client/cli/tx_vote.go
- x/token/types/token.go
Close: #366 
______
For Admin Use:
> OPTIMIZE: make invalid addr valid in cli example client

- go.mod
- go.sum
- x/ammswap/keeper/keeper.go
- x/ammswap/types/expected_keepers.go
- x/staking/keeper/pool.go
- x/staking/types/expected_keepers.go
- x/token/expected_keepers.go
- x/token/keeper.go
> FINISH: refactor for supply module

- go.mod
- go.sum
> change cosmos-sdk to v0.37.9-okexchain6

- x/farm/abci_test.go
- x/farm/client/utils/utils.go
- x/farm/genesis.go
- x/farm/handler_pool.go
- x/farm/handler_test.go
- x/farm/keeper/calc.go
- x/farm/keeper/calc_test.go
- x/farm/keeper/farm_pool.go
- x/farm/keeper/historical_reward_test.go
- x/farm/keeper/invariants.go
- x/farm/keeper/proposal.go
- x/farm/keeper/proposal_test.go
- x/farm/keeper/querier_test.go
- x/farm/keeper/test_common.go
- x/farm/types/earnings.go
- x/farm/types/farm_pool.go
- x/farm/types/farm_pool_test.go
- x/farm/types/historical_reward.go
- x/farm/types/lock_info.go
- x/farm/types/msg.go
- x/farm/types/msg_test.go
- x/farm/types/params.go
- x/farm/types/yielded_token_info.go
> add type SysCoins = DecCoins

- x/token/test_common.go
- x/token/token_test.go
> rm staking from token

- x/genutil/alias.go
> fix genutil validate genesis failed

- cmd/okexchaind/rest.go
> modify the args of RegisterRoutes

- x/token/handler.go
> optimize checking upper bound for minting token

- go.mod
- go.sum
- x/ammswap/types/expected_keepers.go
- x/ammswap/types/params.go
- x/evm/keeper/keeper.go
- x/evm/types/journal_test.go
- x/farm/types/expected_keepers.go
- x/gov/types/params.go
- x/params/proposal_handler.go
- x/params/subspace/alias.go
- x/params/types/alias.go
- x/staking/keeper/keeper.go
- x/staking/keeper/params.go
- x/staking/keeper/test_common.go
- x/staking/simulation/operations.go
- x/staking/types/params.go
…except parasm module
______
For Admin Use:
> change import cosmso-sdk/x/params to okexchain/x/params in okexchain except parasm module

- x/farm/handler_test.go
- x/farm/types/msg.go
- x/farm/types/msg_test.go
> add a MsgProvide validate check, and optimize ut

- .circleci/config.yml
- app/ante/ante_test.go
- app/app_test.go
- app/crypto/hd/algorithm_test.go
- app/simulation_test.go
- app/types/account_test.go
- app/types/config.go
- app/types/config_test.go
- go.mod
- go.sum
> disable failed ut 

- x/backend/types/tx.go
- x/backend/types/tx_test.go
- x/farm/keeper/calc_test.go
- x/farm/keeper/test_common.go
- x/farm/types/farm_pool_test.go
- x/staking/client/cli/tx.go
> update the way to construct SysCoin

- app/ante/eth.go
- x/evm/types/params_test.go
- x/evm/types/state_transition_test.go
Linked with issue ：https://github.com/okex/ethermint/issues/61
______
For Admin Use:
> fix UT of evm, fix gas computer error during send native token

- app/ante/eth.go
- x/evm/types/journal.go
- x/evm/types/state_object.go
- x/evm/types/statedb.go
> Int to Dec

- app/rpc/namespaces/eth/filters/api.go
- cmd/okexchaind/rest.go
- go.mod
- go.sum
> run rest server in okchaind

- go.mod
- go.sum
> display eth address

- x/farm/handler_test.go
- x/farm/keeper/farm_pool.go
- x/farm/keeper/farm_pool_test.go
- x/farm/keeper/whitelist.go
- x/farm/types/msg.go
- x/farm/types/msg_test.go
- x/token/handler.go
https://github.com/okex/okexchain/pull/398's double commit.
______
For Admin Use:
> fix bugs found by audit

- .circleci/config.yml
> open app ut in circleci

- cmd/okexchaincli/main.go
- cmd/okexchaind/main.go
> change env prefix to OKEXCHAIN

- .circleci/config.yml
- x/ammswap/handler_test.go
- x/distribution/keeper/allocation_test.go
- x/staking/keeper/weight.go
> fix precision for calculateWeight

- cmd/okexchaincli/main.go
- cmd/okexchaind/main.go
- x/ammswap/handler.go
- x/common/util.go
- x/dex/handler.go
- x/farm/handler.go
- x/order/handler.go
- x/token/handler.go
> Sanity Check Handler

- x/farm/handler_pool.go
- x/farm/types/errors.go
> optimize error msg

- .circleci/config.yml
- x/backend/mock_test.go
> fixed backend ut

- cmd/okexchaind/main.go
- cmd/okexchaind/replay.go
> local replay

- x/order/keeper/fee.go
> Modify the minimum deal fee judgment

- x/farm/handler_lock.go
- x/farm/handler_pool.go
- x/farm/keeper/calc.go
- x/farm/keeper/earnings.go
- x/farm/keeper/querier.go
- x/farm/types/errors.go
> fix farm bugs merged to master
